GET https://incurred-expiration-renewable-interior.trycloudflare.com/api/media/tree HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImV4cCI6MTc3MzM5NjU5NX0.0r2P66JwAUmcP90g-Epm8yAJ7OGCpDyybjRrlLtyV6k